### ISSUE TITLE
問題の種類をtop画面から選択できるようにする

### ISSUE THREAD

**Issue by aki5648237** [aki5648237/interval-training#15]
■top画面から問題の種類を(3種類,5種類,7種類)から選択可能にした。
- getQuestionDataファイルで処理

**Comment by Y-yomogi** [comment]
const MAJOR_3RD = 'Major 3rd';
const PERFECT_5TH = 'Perfect 5th';
const PETTERN_1 : string[] = [MAJOR_3RD, PERFECT_5TH];

export const GetQuestionData = (questionType : number) => {

	// const questionType : number = 3;
	const questions : Question[] =[];

	switch (questionType) {
		case 1 :
            for(let i = 0; i< PETTERN_1.length; i++){
                questions.push(copyData(PETTERN_1[i]));
            }
            break;
			
	}


	return questions;
}

function copyData(data : string) {
    let obj : Question = {answerText: data, value: 0, result: '', missCount: 0}

    return obj;
}
