### ISSUE TITLE
結果画面に表示する内容を決める

### ISSUE THREAD

**Issue by aki5648237** [aki5648237/interval-training#16]

**Comment by Y-yomogi** [comment]
■簡易と詳細の結果を表示する

■表示内容
- 簡易
  - 得点（100点満点）
  - 全体の間違えた回数
  - 一発での正答数
  - リプレイ数
 
- 詳細
  - 問題の種類
  - 種類ごとのミス数
  - 種類ごとのリプレイ数
  - 種類ごとの正解数(%) 

■簡易表示の得点計算ロジック

- 100点満点で点数は減点方式とする(小数点は少数第一位で繰り上げ)
  - ミス数とリプレイ数での減点 
- 1問の配点は100/問題数
  - 5→1問20点
  -  10→1問10点
  - 20→1問5点
- ミスの減点率
  - 1回ミス
    -  7/10点
  - 2回ミス
    - 4/10点
  - 3回以上ミス(固定)
    - 1/10点 
  - 正解しないかった場合(スキップ)
    -  0点
- リプレイ数による減点率(満点時のみ)
  - 0回
    -  減点なし
  - 1回
    - 9/10点
  - 2回以上(固定)
    - 8/10点 
 
■計算処理ファイル構造
- function内
```
.
├── common
│   ├── detailResultCalculate.tsx
│   ├── setResultData.tsx
│   └── simpleResultCalculate.tsx
└── intervalQuizResult.tsx
```
- contents内
```
.
└── intervalQuizResultContents.tsx
```

**Comment by Y-yomogi** [comment]
result = [{
  type: 1,
  missCount: 0,
  replayCount: 0
}]
